//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MauSuji.rc
//
#define IDC_BUTTON_TARGETUP             3
#define IDC_BUTTON_COMMANDEDIT          4
#define IDC_BUTTON_COMMANDDELETE        5
#define IDC_BUTTON_TARGETDOWN           6
#define IDC_BUTTON_TARGETEDIT           7
#define IDC_BUTTON_TARGETDELETE         8
#define IDC_BUTTON_ACTIONEDIT           9
#define IDC_BUTTON_ACTIONDELETE         10
#define IDD_DIALOG_INIEDIT              101
#define IDD_DIALOG_TARGET               102
#define IDD_DIALOG_ACTION               103
#define IDD_DIALOG_COMMAND              104
#define IDI_ICON1                       105
#define IDI_ICON2                       106
#define IDR_TRAYMENU                    107
#define IDR_DIALOGMENU                  108
#define IDD_DIALOG_NAVIEDIT             109
#define IDD_DIALOG_QUANTITY             110
#define IDD_DIALOG_VERSION              111
#define IDD_DIALOG_OPTION               112
#define IDD_DIALOG_GENERAL              113
#define IDD_DIALOG_GESTURETRAIL         114
#define IDD_DIALOG_TAGETEDITOR          115
#define IDI_FINDER1                     116
#define IDI_FINDER2                     117
#define IDI_FINDER                      118
#define IDR_CONFIGXML                   119
#define IDC_LIST_TARGET                 1004
#define IDC_LIST_ACTION                 1005
#define IDC_EDIT_TARGETFILE             1006
#define IDC_EDIT_CODE                   1009
#define IDC_LIST_COMMAND                1010
#define IDC_COMBO_TARGET                1011
#define IDC_BUTTON_FULLPATH             1012
#define IDC_EDIT_BUTTONCODE             1013
#define IDC_COMBO_COMMAND               1014
#define IDC_BUTTON_BUTTONCAPTURE        1015
#define IDC_BUTTON_FILESEARCH           1016
#define IDC_BUTTON_SETFILENAME          1017
#define IDC_COMBO_SENDKEY               1018
#define IDC_COMBO_ZORDER                1019
#define IDC_STATIC_SENDKEY              1020
#define IDC_EDIT_CMDLINE                1021
#define IDC_EDIT_FILEPATH               1022
#define IDC_EDIT_WAIT                   1023
#define IDC_STATIC_BUTTONCODE           1025
#define IDC_STATIC_FILEPATH             1026
#define IDC_STATIC_CMDLINE              1027
#define IDC_BUTTON_COMMANDUP            1028
#define IDC_BUTTON_COMMANDDOWN          1029
#define IDC_STATIC_COMMANDTARGET        1030
#define IDC_EDIT_COMMENT                1031
#define IDC_STATIC_ZORDER               1032
#define IDC_STATIC_ALPHA1               1033
#define IDC_STATIC_ALPHA2               1034
#define IDC_STATIC_ALPHA3               1035
#define IDC_SCROLLBAR_ALPHA             1036
#define IDC_EDIT_ALPHA                  1037
#define IDC_BUTTON_TARGETSEARCH         1038
#define IDC_COMBO_TARGETTYPE            1039
#define IDC_COMBO_DEFAULTTHRU           1040
#define IDC_STATIC_POS                  1041
#define IDC_COMBO_ETCTARGET             1042
#define IDC_EDIT_POSX                   1043
#define IDC_STATIC_POSX                 1044
#define IDC_STATIC_POSY                 1045
#define IDC_EDIT_POSY                   1046
#define IDC_BUTTON_WINDOWCAPTURE        1047
#define IDC_SCROLLBAR_MOVEQUANTITY      1048
#define IDC_EDIT_MOVEQUANTITY           1049
#define IDC_SCROLLBAR_GESTURETIMEOUT    1050
#define IDC_EDIT_GESTURETIMEOUT         1051
#define IDC_SCROLLBAR_STARTQUANTITY     1052
#define IDC_EDIT_STARTQUANTITY          1053
#define IDC_SCROLLBAR_CORNERTIME        1054
#define IDC_EDIT_CORNERTIME             1055
#define IDC_SCROLLBAR_CORNERPOSX        1056
#define IDC_EDIT_CORNERPOSX             1057
#define IDC_SCROLLBAR_CORNERPOSY        1058
#define IDC_EDIT_CORNERPOSY             1059
#define IDC_EDIT_GESTURECURSOR          1060
#define IDC_BUTTON_GESTURECURSOR        1061
#define IDC_EDIT_WAITCURSOR             1062
#define IDC_BUTTON_WAITCURSOR           1063
#define IDC_SCROLLBAR_NAVIWIDTH         1064
#define IDC_RADIO_TOPLEFT               1065
#define IDC_EDIT_NAVIWIDTH              1066
#define IDC_RADIO_L                     1067
#define IDC_RADIO_M                     1068
#define IDC_RADIO_R                     1069
#define IDC_RADIO_X1                    1070
#define IDC_RADIO_X2                    1071
#define IDC_RADIO_TOP_A                 1072
#define IDC_RADIO_TOP_B                 1073
#define IDC_RADIO_TOP_C                 1074
#define IDC_RADIO_TOPRIGHT              1075
#define IDC_RADIO_LEFT_A                1076
#define IDC_RADIO_LEFT_B                1077
#define IDC_RADIO_LEFT_C                1078
#define IDC_RADIO_RIGHT_A               1079
#define IDC_RADIO_RIGHT_B               1080
#define IDC_RADIO_RIGHT_C               1081
#define IDC_RADIO_BOTTOMLEFT            1082
#define IDC_RADIO_BOTTOM_A              1083
#define IDC_RADIO_BOTTOM_B              1084
#define IDC_RADIO_BOTTOM_C              1085
#define IDC_RADIO_BOTTOMRIGHT           1086
#define IDC_RADIO_WHEELUP               1087
#define IDC_RADIO_WHEELDOWN             1088
#define IDC_RADIO_WHEELLEFT             1089
#define IDC_RADIO_WHEELRIGHT            1090
#define IDC_BUTTON_UP                   1091
#define IDC_BUTTON_RIGHT                1092
#define IDC_BUTTON_LEFT                 1093
#define IDC_BUTTON_DOWN                 1094
#define IDC_BUTTON_TOWHEELUP            1095
#define IDC_BUTTON_TOWHEELDOWN          1096
#define IDC_BUTTON_TOWHEELLEFT          1097
#define IDC_BUTTON_TOWHEELRIGHT         1098
#define IDC_BUTTON_TOL                  1099
#define IDC_BUTTON_TOM                  1100
#define IDC_BUTTON_TOR                  1101
#define IDC_BUTTON_TOX1                 1102
#define IDC_BUTTON_TOX2                 1103
#define IDC_BUTTON_CLEAR                1104
#define IDC_CHECK_HOOKTYPE              1105
#define IDC_CHECK_WHEELREDIRECT         1106
#define IDC_BUTTON_CHOOSEFONT           1107
#define IDC_SCROLLBAR_CLICKWAIT         1108
#define IDC_EDIT_CLICKWAIT              1109
#define IDC_COMBO_NAVITYPE              1110
#define IDC_BUTTON_CHOOSEBACKCOLOR      1111
#define IDC_STATIC_BACKCOLOR            1112
#define IDC_SCROLLBAR_NAVIDELETETIME    1113
#define IDC_EDIT_NAVIDELETETIME         1114
#define IDC_BUTTON_CHOOSEMAINCOLOR      1115
#define IDC_STATIC_MAINCOLOR            1116
#define IDC_BUTTON_CHOOSESUBCOLOR       1117
#define IDC_STATIC_SUBCOLOR             1118
#define IDC_EDIT_NAVITITLE              1119
#define IDC_STATIC_FONT                 1120
#define IDC_SCROLLBAR_TIPLOCATEX        1121
#define IDC_EDIT_TIPLOCATEX             1122
#define IDC_SCROLLBAR_TIPLOCATEY        1123
#define IDC_EDIT_TIPLOCATEY             1124
#define IDC_CHECK_GETFILE               1125
#define IDC_EDIT_TARGETCLASS            1126
#define IDC_CHECK_ALPHA                 1127
#define IDC_CHECK_GETCLASS              1128
#define IDC_CHECK_CTRL                  1129
#define IDC_CHECK_CONTROL               1130
#define IDC_CHECK_SHIFT                 1131
#define IDC_COMBO_SCROLL                1132
#define IDC_STATIC_SCROLL               1133
#define IDC_SCROLLBAR_SCROLL            1134
#define IDC_EDIT_SCROLL                 1135
#define IDC_CHECK_MODIFIERKEY           1136
#define IDC_BUTTON_UPLEFT               1137
#define IDC_BUTTON_UPRIGHT              1138
#define IDC_BUTTON_DOWNLEFT             1139
#define IDC_BUTTON_DOWNRIGHT            1140
#define IDC_STATIC_MESSAGE              1141
#define IDC_EDIT_MESSAGE                1142
#define IDC_COMBO_MESSAGE               1143
#define IDC_STATIC_WPARAM               1144
#define IDC_EDIT_WPARAM                 1145
#define IDC_COMBO_WPARAM                1146
#define IDC_STATIC_LPARAM               1147
#define IDC_EDIT_LPARAM                 1148
#define IDC_COMBO_LPARAM                1149
#define IDC_STATIC_COPY                 1150
#define IDC_EDIT_COPY                   1151
#define IDC_COMBO_COMMANDTARGET         1152
#define IDC_CHECK_GETID                 1153
#define IDC_EDIT_TARGETID               1154
#define IDC_STATIC_S_SCROLL             1155
#define IDC_STATIC_S_SCROLLLINE         1156
#define IDC_EDIT_S_SCROLLLINE           1157
#define IDC_STATIC_S_SCROLLPAGE         1158
#define IDC_EDIT_S_SCROLLPAGE           1159
#define IDC_SCROLLBAR_CHECKINTERVAL     1160
#define IDC_EDIT_CHECKINTERVAL          1161
#define IDC_SCROLLBAR_SCROLLSENSITIVITY 1162
#define IDC_EDIT_SCROLLSENSITIVITY      1163
#define IDC_SCROLLBAR_KURUKURUTIMEOUT   1164
#define IDC_EDIT_KURUKURUTIMEOUT        1165
#define IDC_SCROLLBAR_CIRCLERATE        1166
#define IDC_EDIT_CIRCLERATE             1167
#define IDC_CHECK_FREESCROLL            1168
#define IDC_EDIT_TARGETCOMMENT          1169
#define IDC_EDIT_OPENMAUSUJI_VERSION    1170
#define IDC_EDIT_MAUSUJI_VERSION        1171
#define IDC_BUTTON_TARGETADD            1172
#define IDC_BUTTON_ACTIONADD            1173
#define IDC_BUTTON_COMMANDADD           1174
#define IDC_TREE_PAGE                   1175
#define IDC_STATIC_PAGE                 1176
#define IDC_BUTTON_EXIT                 1177
#define IDC_BUTTON_HELP                 1178
#define IDC_BUTTON_VERSION              1179
#define IDC_CHECKBOX_MOUSEHOOK          1180
#define IDC_CHECKBOX_WHEELREDIRECT      1181
#define IDC_CHECKBOX_CURSORCHANGE       1182
#define IDC_CHECKBOX_SHOWTASKTRAY       1183
#define IDC_CHECKBOX_HIGH_PRIORITY      1184
#define IDC_RADIO_GESTUREDIRECTION_4    1185
#define IDC_RADIO_GESTUREDIRECTION_8    1186
#define IDC_RADIO_GESTUREDIRECTION_84   1187
#define IDC_RADIO_GESTUREDIRECTION_44   1188
#define IDC_CHECKBOX_TIMEOUTTYPE        1189
#define IDC_CHECKBOX_WHEELACTIVE        1190
#define IDC_CHECKBOX_KURUKURU           1191
#define IDC_CHECKBOX_DEFAULTHOOKTYPE    1194
#define IDC_CHECKBOX_DEFAULTWHEELREDIRECT   1195
#define IDC_CHECKBOX_FREESCROLLMODE     1196
#define IDC_CHECKBOX_GESTURETRAIL       1197
#define IDC_SLIDER_GESTURETRAILWIDTH    1198
#define IDC_EDIT_GESTURETRAILWIDTH      1199
#define IDC_STATIC_GESTURETRAILCOLOR    1200
#define IDC_BUTTON_GESTURETRAILCOLOR    1201
#define IDC_RADIO_GESTURETRAILMODE_AUTO 1202
#define IDC_RADIO_GESTURETRAILMODE_DESKTOP  1203
#define IDC_RADIO_GESTURETRAILMODE_LAYEREDWINDOW    1204
#define IDC_BUTTON_TARGETCOPY           1205
#define IDC_BUTTON_TARGETIMPORT         1206
#define IDC_BUTTON_TARGETEXPORT         1207
#define IDC_EDIT_TARGET                 1208
#define IDC_STATIC_FINDER               1209
#define IDC_STATIC_BACKGROUND           1210
#define IDC_SLIDER_NAVIDELETETIME       1211
#define IDC_SLIDER_NAVIWIDTH            1212
#define IDC_SLIDER_TIPLOCATEX           1213
#define IDC_SLIDER_TIPLOCATEY           1214
#define IDC_SLIDER_CHECKINTERVAL        1215
#define IDC_SLIDER_MOVEQUANTITY         1216
#define IDC_SLIDER_GESTURETIMEOUT       1217
#define IDC_SLIDER_STARTQUANTITY        1218
#define IDC_SLIDER_CORNERTIME           1219
#define IDC_SLIDER_CORNERPOSX           1220
#define IDC_SLIDER_CORNERPOSY           1221
#define IDC_SLIDER_CLICKWAIT            1222
#define IDC_SLIDER_SCROLLSENSITIVITY    1223
#define IDC_SLIDER_CIRCLERATE           1224
#define IDC_SLIDER_KURUKURUTIMEOUT      1225
#define IDC_SLIDER_ALPHA                1226
#define IDC_SLIDER_SCROLL               1227
#define IDC_EDIT_TARGEWINDOWTTITLE      1228
#define IDC_CHECK_GETWINDOWTITLE        1229
#define IDC_RADIO_NAVITYPE_NONE         1230
#define IDC_RADIO_NAVITYPE_FIXED        1231
#define IDC_RADIO_NAVITYPE_FLOAT        1232
#define IDC_STATIC_FRAMECOLOR           1233
#define IDC_BUTTON_CHOOSEFRAMECOLOR     1234

#define IDM_SHOWDIALOG                  40001
#define IDM_ENDMAUSUJI                  40003
#define IDM_DEFAULTHOOKTYPE             40004
#define IDM_CURSORCHANGE                40005
#define IDM_SHOWTASKTRAY                40006
#define IDM_SHOWMAUSUJINAVI             40008
#define IDM_HIDEMAUSUJINAVI             40009
#define IDM_TIPMAUSUJINAVI              40010
#define IDM_OPENHELP                    40011
#define IDM_MOUSEHOOK                   40012
#define IDM_VERSIONINFO                 40013
#define IDM_WHEELREDIRECT               40019
#define IDM_DEFAULTWHEELREDIRECT        40020
#define IDM_WHEELACTIVE                 40023
#define IDM_TIMEOUTTYPE                 40024
#define IDM_DM9x                        40025
#define IDM_NAVIEDIT                    40026
#define IDM_QUANTITY                    40027
#define IDM_GESTUREDIRECTION_8          40032
#define IDM_GESTUREDIRECTION_4          40034
#define IDM_GESTUREDIRECTION_84         40037
#define IDM_GESTUREDIRECTION_44         40038
#define IDM_HIGH_PRIORITY               40040
#define IDM_FREESCROLLMODE              40041
#define IDM_KURUKURU                    40042
#define IDM_TARGET_LISTVIEW             40043
#define IDM_TARGET_TREEVIEW             40044
#define IDM_IMPORTSETTING               40045
#define IDM_EXPORTSETTING               40046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40047
#define _APS_NEXT_CONTROL_VALUE         1235
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
